# Generated by Django 5.0.1 on 2024-02-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CCTVCamera',
            new_name='CCTVCameras',
        ),
        migrations.RenameModel(
            old_name='ManufacturerNetDev',
            new_name='CCTVManufacturers',
        ),
        migrations.RenameModel(
            old_name='CCTVRecorder',
            new_name='CCTVRecorders',
        ),
        migrations.RenameModel(
            old_name='ManufacturerCCTV',
            new_name='CCTVTypes',
        ),
        migrations.RenameModel(
            old_name='ControlPanelModel',
            new_name='ControlPanelModels',
        ),
        migrations.RenameModel(
            old_name='ControlPanel',
            new_name='ControlPanels',
        ),
        migrations.RenameModel(
            old_name='TypeNetDev',
            new_name='NetDevManufacturers',
        ),
        migrations.RenameModel(
            old_name='TypeCCTV',
            new_name='NetDevTypes',
        ),
        migrations.RenameModel(
            old_name='NetworkDevice',
            new_name='NetworkDevices',
        ),
        migrations.RenameModel(
            old_name='NWD_Model',
            new_name='NWD_Models',
        ),
    ]
