# Generated by Django 5.0.1 on 2024-02-16 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_db', '0002_rename_cctvcamera_cctvcameras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cctvcameras',
            name='id_cctv_system_manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects_db.cctvmanufacturers'),
        ),
        migrations.AlterField(
            model_name='cctvcameras',
            name='id_cctv_system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects_db.cctvtypes'),
        ),
        migrations.AlterField(
            model_name='cctvrecorders',
            name='id_cctv_system_manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects_db.cctvmanufacturers'),
        ),
        migrations.AlterField(
            model_name='cctvrecorders',
            name='id_cctv_system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects_db.cctvtypes'),
        ),
        migrations.AlterField(
            model_name='nwd_models',
            name='nwd_manufacturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects_db.netdevmanufacturers'),
        ),
        migrations.AlterField(
            model_name='nwd_models',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects_db.netdevtypes'),
        ),
    ]
