# Generated by Django 5.0.1 on 2024-02-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects_db', '0003_alter_cctvcameras_id_cctv_system_manufacturer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nwd_models',
            name='id_system',
        ),
        migrations.AddField(
            model_name='controlpanels',
            name='id_system',
            field=models.ForeignKey(default=55, on_delete=django.db.models.deletion.CASCADE, to='objects_db.systems'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemtypes',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='systemtypes',
            name='table',
            field=models.CharField(default='Table', max_length=40),
            preserve_default=False,
        ),
    ]
