# Generated by Django 5.0.1 on 2024-02-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects_db', '0004_remove_nwd_models_id_system_controlpanels_id_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlpanels',
            old_name='id_system',
            new_name='system',
        ),
    ]
